In [1]:
# divide the data into batches and using mini batch gradient descent
#dataset and dataloader classes

In [ ]:
# dataset class load the data, data load and returned. 3 methods in this class:__init__(), __len__(), __getitem__(index)
# dataloader class calls data index shuffle it and make the chunks combined in a batch.


In [1]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import Dataset, DataLoader

In [2]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [4]:
print(X)
print(y)
print(X.shape)

[[ 1.06833894 -0.97007347]
 [-1.14021544 -0.83879234]
 [-2.8953973   1.97686236]
 [-0.72063436 -0.96059253]
 [-1.96287438 -0.99225135]
 [-0.9382051  -0.54304815]
 [ 1.72725924 -1.18582677]
 [ 1.77736657  1.51157598]
 [ 1.89969252  0.83444483]
 [-0.58723065 -1.97171753]]
[1 0 0 0 0 1 1 1 1 0]
(10, 2)


In [5]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

print(X)
print(y)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])


In [9]:
class CustomDataset(Dataset):
  def __init__(self,Features,labels):
    self.Features=Features
    self.labels=labels

  def __len__(self):
    return len(self.Features)

  def __getitem__(self, index):
    #can apply transformations here.
    return self.Features[index] , self.labels[index]


dataset=CustomDataset(X,y)
len(dataset)


10

In [10]:
dataLoader=DataLoader(dataset, batch_size=2, shuffle=True)
for batch_features, batch_labels in dataLoader:
  print(batch_features)
  print(batch_labels)


tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]])
tensor([0, 1])
tensor([[ 1.8997,  0.8344],
        [ 1.0683, -0.9701]])
tensor([1, 1])
tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]])
tensor([0, 1])
tensor([[ 1.7774,  1.5116],
        [-1.9629, -0.9923]])
tensor([1, 0])
tensor([[-0.5872, -1.9717],
        [-1.1402, -0.8388]])
tensor([0, 0])


In [ ]:
#use the parallelism using the workers by defining the num_workers parameter in the DataLoader.
# pin_memory=True, drop_last, collate_fn, sampler- more parameters in the dataloader class.

In [ ]:
# sampler- sequential and random sampler (used for sampling the data and helps in dataset loading.) can alsp create the custom samplers as per the need.

In [ ]:
# collate_fn combines the chunks into a single batch.