In [5]:
#The torch.nn module in PyTorch provides the essential building blocks for creating and training neural networks.
#It defines the nn.Module base class, which is the foundational element for all network layers and models.

In [23]:
#build a nn using nn module single neuron.
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__() #child class
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out


In [24]:
features=torch.rand(10,5)# five inputs
model=Model(features.shape[1])

model(features)

tensor([[0.6091],
        [0.6289],
        [0.5425],
        [0.5578],
        [0.5234],
        [0.5415],
        [0.4867],
        [0.5887],
        [0.5542],
        [0.6847]], grad_fn=<SigmoidBackward0>)

In [25]:
print(model.linear.bias)
print(model.linear.weight)

Parameter containing:
tensor([0.0361], requires_grad=True)
Parameter containing:
tensor([[ 0.3947,  0.3365, -0.4457,  0.2901,  0.0735]], requires_grad=True)


In [28]:
!pip install torchinfo
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [10]:
## nn with an hidden layer with 18weights and 4 bias
# hidden layer use relu and output activation using sigmoid activation function.
import torch
import torch.nn as nn
class Model2(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear1=nn.Linear(num_features,3)#layer 1
    self.relu=nn.ReLU()

    self.linear2=nn.Linear(3,1) # layer 2
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out



In [11]:
features=torch.rand(10,5)

model=Model2(features.shape[1])
model(features)

tensor([[0.6125],
        [0.6024],
        [0.5813],
        [0.5881],
        [0.6132],
        [0.6220],
        [0.6146],
        [0.6279],
        [0.6055],
        [0.5887]], grad_fn=<SigmoidBackward0>)

In [21]:
!pip install torchinfo
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [25]:
# use of nn.Sequential in model defining (sequential container)

class Model3(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network
    return out



In [31]:
features=torch.rand(10,5)

model3=Model3(features.shape[1])
model3(features)

Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)